import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useRef, useState } from "react";
import styles from '@/styles/Home.module.css'
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [Description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);
  const [Result, setResult] = useState('');
  const handleDescriptionChange = (event: any) => {
    setDescription(event.target.value);
  };
  const generateResult = async (e: any) => {
    e.preventDefault();
    setLoading(true);
    const dataInp = {
      prompt: Description,
    };
    axios.post('/api/generate', dataInp)
    .then(response => {
      const dresponse = response.data;
     
      setResult(dresponse.outputText);
      setLoading(false);
    })
    .catch(error => {
      if (error.response) {
        console.log(error.response.status);
        console.log(error.response.data);
      } else {
        console.log(error.message);
      }
      setLoading(false);
    });

  
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='container mx-auto bg-white rounded-md'>
          <div className='flex flex-col items-center justify-center p-4 space-y-4 w-full'>
          <div className='w-full'>
            <label htmlFor="storyDescription" className="block text-sm font-medium leading-6 text-gray-900">
              What do you want to tweet
            </label>
            <div className=" w-full">
              <textarea
                id="storyDescription"
                name="storyDescription"
                value={Description}
                onChange={handleDescriptionChange}


                required
                className="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
              />
            </div>
          </div>

          <button
            type="button" onClick={generateResult}
            className="rounded-md ml-auto bg-indigo-700 py-1.5 px-2.5 mt-4 font-semibold  text-white shadow-sm hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
          >
            
                <span>Generate</span>
            

          </button>

          </div>
          <div className='min-w-[400px] bg-white rounded-md'>
{Result}
          </div>

        </div>
     
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
